"""One-off: generate the full first-pass FBDI_to_Applaud_AppMap.xlsx from the
ApplicationSpec data pulled live (2026-06-03). Imports follow the uniform rule
(each I_T_* app -> one IF step = itself); exports are per-app EF lists, with
real exceptions (renamed/no-X_ EFs, multi-EF, cross-refs) captured explicitly.
derive_appmap filters to the mapped T_ tables and excludes *_VAL by default.
Not part of the package — kept for provenance / re-run.
"""
from fbdi.report import load_mapping
from fbdi.applaud_appmap import derive_appmap, write_appmap_workbook

# --- Import apps: every I_T_* app has a single IF step equal to its own name ---
I_APPS = [
    "I_T_AP_INVOICE_ATTACHMENTS","I_T_AP_INVOICE_INT","I_T_AP_INVOICE_LINES","I_T_AR_RECEIPTS",
    "I_T_AWARD_BUDGET_PERIODS","I_T_AWARD_CERTIFICATIONS","I_T_AWARD_FED_DOM_ASSIST_PRG",
    "I_T_AWARD_FUNDING","I_T_AWARD_FUNDING_ALLOCATIONS","I_T_AWARD_FUNDING_SOURCE",
    "I_T_AWARD_KEYWORDS","I_T_AWARD_ORGANIZATION_CREDITS","I_T_AWARD_PERSONNEL",
    "I_T_AWARD_PRJ_FUND_SRC","I_T_AWARD_PRJ_TASK_BURDEN_SCH","I_T_AWARD_PROJECTS",
    "I_T_AWARD_REFERENCES","I_T_AWARD_TERMS_CONDITIONS","I_T_AWARDS",
    "I_T_BANKS","I_T_BANKS_BRANCHES","I_T_BPA_PO_GA_ORG_ASSIGN_INTER","I_T_BPA_PO_HEADERS_INTERFACE",
    "I_T_BPA_PO_LINE_LOCATIONS","I_T_BPA_PO_LINES_INTERFACE",
    "I_T_CONTACTS","I_T_CONTRACT_HDR_FLEX_P","I_T_CONTRACT_HDR_P","I_T_CONTRACT_HDRACTIVATE_P",
    "I_T_CONTRACT_LINES_P","I_T_CONTRACT_PARTY_CONTACT_P","I_T_CONTRACT_PARTY_P",
    "I_T_CSE_ASSETS_INT","I_T_CSE_INT_BATCHES_B","I_T_CST_I_INCOMING_TXN_COSTS",
    "I_T_CST_INTR_STD_COST_DETAIL","I_T_CST_INTR_STD_COST_HEADERS","I_T_CUSTOMERS",
    "I_T_DOO_ORDER_ADDRESSES_INT","I_T_DOO_ORDER_CHARGE_COMPS","I_T_DOO_ORDER_CHARGES_INT",
    "I_T_DOO_ORDER_HDRS_ALL_EFF_B","I_T_DOO_ORDER_HEADERS_ALL","I_T_DOO_ORDER_LINES_ALL",
    "I_T_DOO_ORDER_LINES_EFF_B",
    "I_T_EGO_CHANGE_ATTACHMENTS_INT","I_T_EGO_CHANGE_LINES_INT","I_T_EGO_CHANGES_INT",
    "I_T_EGO_ITEM_INTF_EFF_B","I_T_EGP_COMPONENTS_INTERFACE","I_T_EGP_ITEM_ATTACHMENTS_INTF",
    "I_T_EGP_ITEM_CATEGORIES_INT","I_T_EGP_ITEM_RELATIONSHIPS_INT","I_T_EGP_ITEM_REVISION_INT",
    "I_T_EGP_REF_DESGS_INTERFACE","I_T_EGP_STRUCTURES_INTERFACE","I_T_EGP_SUB_COMPS_INTERFACE",
    "I_T_EGP_SYSTEM_ITEMS_INTERFACE","I_T_EGP_TRADING_PARTNER_ITEMS",
    "I_T_FA_ADJUSTMENTS","I_T_FA_DISPOSALS","I_T_FA_MASS_ADDITIONS","I_T_FA_MASSADD_DISTRIBUTIONS",
    "I_T_FA_MC_MASS_RATES",
    "I_T_GL_INTERFACE","I_T_GL_SEGMENT_VALUES","I_T_GMS_PERSONNEL_INT","I_T_GMS_SPONSORS_INT",
    "I_T_HZ_IMP_ACCOUNTRELS_T","I_T_HZ_IMP_ACCOUNTS_T","I_T_HZ_IMP_ACCTCONTACTS_T",
    "I_T_HZ_IMP_ACCTSITES_T","I_T_HZ_IMP_ACCTSITEUSES_T","I_T_HZ_IMP_CONTACTPTS_T",
    "I_T_HZ_IMP_CONTACTROLES","I_T_HZ_IMP_CONTACTS_T","I_T_HZ_IMP_LOCATIONS_T",
    "I_T_HZ_IMP_PARTIES_T","I_T_HZ_IMP_PARTY_SITES_T","I_T_HZ_IMP_RELSHIPS_T","I_T_HZ_IMP_ROLERESP",
    "I_T_IBY_TEMP_EXT_BANK_ACCT","I_T_IBY_TEMP_EXT_PAYEES","I_T_IBY_TEMP_PMT_INSTR_USES",
    "I_T_INV_INVENTORY_LOC","I_T_INV_INVENTORY_SUB","I_T_INV_ITEM_LOCATOR","I_T_INV_ITEM_SUB",
    "I_T_INV_SERIAL_NUMBERS_INT","I_T_INV_TRANSACTION_LOTS_INT","I_T_INV_TRANSACTIONS_INTER",
    "I_T_MSC_ST_ASSIGNMENT_SETS","I_T_MSC_ST_MEASURE_DATA","I_T_MSC_ST_MEASURE_DATA_BOOK",
    "I_T_MSC_ST_SOURCING_RULES",
    "I_T_PJB_BILLING_EVENTS_INT","I_T_PJC_TXN_XFACE_STAGE_ALL","I_T_PJF_PROJ_ELEMENTS_XFACE",
    "I_T_PJO_BUDGETS_XFACE","I_T_PO_DISTRIBUTIONS_INTERFACE","I_T_PO_HEADERS_INTERFACE",
    "I_T_PO_LINE_LOC_INT","I_T_PO_LINES_INTERFACE","I_T_POZ_ADDRESSES_INT",
    "I_T_POZ_SITE_ASSIGNMENTS_INT","I_T_POZ_SUP_BUS_CLASS","I_T_POZ_SUP_CONT_ADDR",
    "I_T_POZ_SUP_CONTACTS","I_T_POZ_SUPPLIER_SITES_INT","I_T_POZ_SUPPLIERS_INT",
    "I_T_PRICING_PROFILE","I_T_PROJ_ENT_RES_INTERFACE","I_T_PROJ_RES_REQ_INTERFACE",
    "I_T_PROJECT_CLASSIFICATIONS","I_T_PROJECT_TEAM_MEMBERS","I_T_PROJECTS",
    "I_T_QP_MATRIX_DIMENSIONS_INT","I_T_QP_MATRIX_RULES_INT","I_T_QP_PL_COMP_ITEMS_INT",
    "I_T_QP_PRICE_LIST_CHARGES_INT","I_T_QP_PRICE_LIST_ITEMS_INT","I_T_QP_PRICE_LIST_SETS_INT",
    "I_T_QP_PRICE_LISTS_INT",
    "I_T_RA_CUSTOMER_PROFILES_INT_A","I_T_RA_INT_DIST_ALL","I_T_RA_INTERFACE_LINES_ALL",
    "I_T_RCV_HEADERS_INTERFACE","I_T_RCV_TRANSACTIONS_INTERFACE","I_T_REFERENCE_ACCOUNTS",
    "I_T_SO_ATTACHMENTS","I_T_TRADING_PARTNERS_IMPORT",
    "I_T_WIE_INT_BATCHES_VL","I_T_WIS_WD_DETAILS_INT-ARES","I_T_WIS_WD_DETAILS_INT-ATOCMP",
    "I_T_WIS_WD_DETAILS_INT-OPS","I_T_WIS_WD_DETAILS_INT-RSC","I_T_WIS_WD_DETAILS_INT-STNDCMP",
    "I_T_WIS_WORK_DEFINITIONS_INT","I_T_WORK_DEFINITION_AND_OPS","I_T_WSH_TRANSIT_TIMES",
]

# --- Export apps whose EF steps are simply [the app's own name] (+ a _VAL the code drops) ---
X_SIMPLE = [
    "X_T_AP_INVOICE_ATTACHMENTS","X_T_AP_INVOICE_LINES","X_T_AR_RECEIPTS",
    "X_T_AWARD_BUDGET_PERIODS","X_T_AWARD_CERTIFICATIONS","X_T_AWARD_FED_DOM_ASSIST_PRG",
    "X_T_AWARD_FUNDING","X_T_AWARD_FUNDING_ALLOCATIONS","X_T_AWARD_FUNDING_SOURCE",
    "X_T_AWARD_KEYWORDS","X_T_AWARD_ORGANIZATION_CREDITS","X_T_AWARD_PERSONNEL",
    "X_T_AWARD_PRJ_FUND_SRC","X_T_AWARD_PRJ_TASK_BURDEN_SCH","X_T_AWARD_PROJECTS",
    "X_T_AWARD_REFERENCES","X_T_AWARD_TERMS_CONDITIONS","X_T_AWARDS",
    "X_T_BPA_PO_GA_ORG_ASSIGN_INTER","X_T_BPA_PO_HEADERS_INTERFACE","X_T_BPA_PO_LINE_LOCATIONS",
    "X_T_BPA_PO_LINES_INTERFACE",
    "X_T_CONTACTS","X_T_CONTRACT_HDR_FLEX_P","X_T_CONTRACT_HDR_P","X_T_CONTRACT_HDRACTIVATE_P",
    "X_T_CONTRACT_LINES_P","X_T_CONTRACT_PARTY_CONTACT_P","X_T_CONTRACT_PARTY_P",
    "X_T_CSE_ASSETS_INT","X_T_CSE_INT_BATCHES_B","X_T_CST_INTR_STD_COST_DETAIL",
    "X_T_CST_INTR_STD_COST_HEADERS",
    "X_T_DOO_ORDER_ADDRESSES_INT","X_T_DOO_ORDER_CHARGE_COMPS","X_T_DOO_ORDER_CHARGES_INT",
    "X_T_DOO_ORDER_HDRS_ALL_EFF_B","X_T_DOO_ORDER_HEADERS_ALL","X_T_DOO_ORDER_LINES_ALL",
    "X_T_DOO_ORDER_LINES_EFF_B","X_T_DOO_ORDER_DOC_REFERENCES",
    "X_T_EGO_CHANGE_ATTACHMENTS_INT","X_T_EGO_CHANGE_LINES_INT","X_T_EGO_CHANGES_INT",
    "X_T_EGO_ITEM_INTF_EFF_B","X_T_EGP_COMPONENTS_INTERFACE","X_T_EGP_ITEM_ATTACHMENTS_INTF",
    "X_T_EGP_ITEM_CATEGORIES_INT","X_T_EGP_ITEM_RELATIONSHIPS_INT","X_T_EGP_ITEM_REVISION_INT",
    "X_T_EGP_REF_DESGS_INTERFACE","X_T_EGP_STRUCTURES_INTERFACE","X_T_EGP_SUB_COMPS_INTERFACE",
    "X_T_EGP_SYSTEM_ITEMS_INTERFACE","X_T_EGP_TRADING_PARTNER_ITEMS",
    "X_T_FA_ADJUSTMENTS","X_T_FA_DISPOSALS","X_T_FA_MASS_ADDITIONS","X_T_FA_MASSADD_DISTRIBUTIONS",
    "X_T_FA_MC_MASS_RATES",
    "X_T_GL_BUDGETS_INTERFACE","X_T_GL_INTERFACE","X_T_GL_SEGMENT_VALUES","X_T_GMS_PERSONNEL_INT",
    "X_T_GMS_SPONSORS_INT",
    "X_T_HZ_IMP_ACCOUNTRELS_T","X_T_HZ_IMP_ACCOUNTS_T","X_T_HZ_IMP_ACCTCONTACTS_T",
    "X_T_HZ_IMP_ACCTSITES_T","X_T_HZ_IMP_ACCTSITEUSES_T","X_T_HZ_IMP_CONTACTPTS_T",
    "X_T_HZ_IMP_CONTACTROLES","X_T_HZ_IMP_CONTACTS_T","X_T_HZ_IMP_LOCATIONS_T",
    "X_T_HZ_IMP_PARTIES_T","X_T_HZ_IMP_PARTY_SITES_T","X_T_HZ_IMP_PARTYSITEUSES_T",
    "X_T_HZ_IMP_RELSHIPS_T","X_T_HZ_IMP_ROLERESP",
    "X_T_IBY_TEMP_EXT_BANK_ACCT","X_T_IBY_TEMP_PMT_INSTR_USES","X_T_INV_INVENTORY_LOC",
    "X_T_INV_INVENTORY_SUB","X_T_INV_ITEM_LOCATOR","X_T_INV_ITEM_SUB","X_T_INV_SERIAL_NUMBERS_INT",
    "X_T_INV_TRANSACTION_LOTS_INT","X_T_INV_TRANSACTIONS_INTER",
    "X_T_MSC_ST_ASSIGNMENT_SETS","X_T_MSC_ST_MEASURE_DATA","X_T_MSC_ST_MEASURE_DATA_BOOK",
    "X_T_MSC_ST_SOURCING_RULES",
    "X_T_PJB_BILLING_EVENTS_INT","X_T_PJC_TXN_XFACE_STAGE_ALL","X_T_PJF_PROJ_ELEMENTS_XFACE",
    "X_T_PJO_BUDGETS_XFACE","X_T_PO_DISTRIBUTIONS_INTERFACE","X_T_PO_HEADERS_INTERFACE",
    "X_T_PO_LINE_LOC_INT","X_T_PO_LINES_INTERFACE","X_T_POZ_SITE_ASSIGN","X_T_POZ_SUP_BUS_CLASS",
    "X_T_POZ_SUP_CONT_ADDR","X_T_POZ_SUP_CONTACTS","X_T_POZ_SUPPLIER_SITES","X_T_POZ_SUPPLIERS",
    "X_T_PRICING_PROFILE","X_T_PROJ_ENT_RES_INTERFACE","X_T_PROJ_RES_REQ_INTERFACE",
    "X_T_PROJECT_CLASSIFICATIONS","X_T_PROJECT_TEAM_MEMBERS","X_T_PROJECTS",
    "X_T_PROJ_CONTRACT_BILL_PLAN","X_T_PROJ_CONTRACT_HDR","X_T_PROJ_CONTRACT_LINES",
    "X_T_PROJ_CONTRACT_PARTY",
    "X_T_QP_MATRIX_DIMENSIONS_INT","X_T_QP_MATRIX_RULES_INT","X_T_QP_PL_COMP_ITEMS_INT",
    "X_T_QP_PRICE_LIST_CHARGES_INT","X_T_QP_PRICE_LIST_ITEMS_INT","X_T_QP_PRICE_LIST_SETS_INT",
    "X_T_QP_PRICE_LISTS_INT",
    "X_T_RA_CUSTOMER_PROFILES_INT_A","X_T_RA_INT_DIST_ALL","X_T_RA_INTERFACE_LINES_ALL",
    "X_T_RCV_HEADERS_INTERFACE","X_T_RCV_TRANSACTIONS_INTERFACE","X_T_REFERENCE_ACCOUNTS",
    "X_T_SO_ATTACHMENTS","X_T_TRADING_PARTNERS_IMPORT",
    "X_T_WIE_INT_BATCHES_VL","X_T_WIS_WD_DETAILS_INT-ARES","X_T_WIS_WD_DETAILS_INT-ATOCMP",
    "X_T_WIS_WD_DETAILS_INT-OPS","X_T_WIS_WD_DETAILS_INT-RSC","X_T_WIS_WD_DETAILS_INT-STNDCMP",
    "X_T_WIS_WORK_DEFINITIONS_INT","X_T_WORK_DEFINITION_AND_OPS","X_T_WSH_TRANSIT_TIMES",
]

# --- Export apps whose EF step(s) differ from the app name (renamed/no-X_/multi-EF/cross-ref) ---
# Full EF lists incl. _VAL (derive_appmap drops *_VAL by default).
X_EXC = {
    "X_T_BANKS": ["T_BANKS", "X_T_BANKS_VAL"],
    "X_T_BANKS_BRANCHES": ["T_BANKS_BRANCHES", "X_T_BANKS_BRANCHES_VAL"],
    "X_T_AP_INVOICE_INT": ["X_T_AP_INVOICE_INT", "X_T_AP_INVOICE_INT_TXT", "X_T_AP_INVOICE_INT_VAL"],
    "X_T_CST_I_INCOMING_TXN_COSTS": ["X_T_CST_I_INCOMING_TXN_COST", "X_T_CST_I_INCOMING_TXN_COS_VAL"],
    "X_T_IBY_TEMP_EXT_PAYEES": ["X_T_IBY_EXT_TEMP_PAYEES", "X_T_IBY_EXT_TEMP_PAYEES_VAL"],
    "X_T_POZ_SUP_ADDRESSES": ["X_T_POZ_SUP_ADDRESSES", "X_T_POZ_SUP_ADDRESSES_VAL", "X_T_POZ_SUP_ADDRESSES_TXT"],
    "X_T_RA_CUSTOMER_BANKS_INT_ALL": ["X_T_RA_CUSTOMER_BANKS_INT_ALL", "CUST_BANKS_API"],
    "X_T_PROJ_CON_PARTY_CONTACT": ["X_T_PROJ_CON_PARTY_CONTACT", "X_T_PROJ_CON_PARTY_CONTACT_CSV"],
    "X_T_CUSTOMERS": ["X_T_CUSTOMERS", "X_T_CONTACTS_VAL"],
}


# Authoritative Application.DBID where it differs from name[2:] (pulled live 2026-06-03).
# Abbreviated app names map to a fuller table DBID; never derive DBID from the name.
DBID_OVERRIDES = {
    "I_T_AWARD_PRJ_FUND_SRC": "T_AWARD_PROJECT_FUNDING_SOURCE",
    "I_T_AWARD_PRJ_TASK_BURDEN_SCH": "T_AWARD_PRJ_TASK_BURDEN_SCHED",
    "I_T_AWARD_TERMS_CONDITIONS": "T_AWARD_TERMS_AND_CONDITIONS",
    "I_T_BPA_PO_GA_ORG_ASSIGN_INTER": "T_BPA_PO_GA_ORG_ASSIGN_INTERFA",
    "I_T_EGP_ITEM_RELATIONSHIPS_INT": "T_EGP_ITEM_RELATIONSHIPS_INTF",
    "I_T_GL_SEGMENT_VALUES": "T_GL_SEGMENT_VALUES_INT",
    "I_T_INV_INVENTORY_LOC": "T_INV_INVENTORY_LOCATOR",
    "I_T_INV_INVENTORY_SUB": "T_INV_INVENTORY_SUBINVENTORY",
    "I_T_INV_ITEM_SUB": "T_INV_ITEM_SUBINVENTORY",
    "I_T_INV_TRANSACTIONS_INTER": "T_INV_TRANSACTIONS_INTERFACE",
    "I_T_MSC_ST_MEASURE_DATA_BOOK": "T_MSC_ST_MEASURE_DATA_BOOKINGS",
    "I_T_PO_LINE_LOC_INT": "T_PO_LINE_LOCATIONS_INTERFACE",
    "I_T_POZ_ADDRESSES_INT": "T_POZ_SUP_ADDRESSES_INT",
    "I_T_POZ_SUP_BUS_CLASS": "T_POZ_SUP_BUS_CLASS_INT",
    "I_T_POZ_SUP_CONT_ADDR": "",   # empty DBID in the MDB — import app maps to no table
    "I_T_POZ_SUP_CONTACTS": "T_POZ_SUP_CONTACTS_INT",
    "I_T_RA_CUSTOMER_PROFILES_INT_A": "T_RA_CUSTOMER_PROFILES_INT_ALL",
    "I_T_RA_INT_DIST_ALL": "T_RA_INTERFACE_DISTRIBUTIONS",
    "I_T_WIS_WD_DETAILS_INT-ATOCMP": "T_WIS_WD_DETAILS_INT-ATO-CMP",
    "X_T_AWARD_PRJ_FUND_SRC": "T_AWARD_PROJECT_FUNDING_SOURCE",
    "X_T_AWARD_PRJ_TASK_BURDEN_SCH": "T_AWARD_PRJ_TASK_BURDEN_SCHED",
    "X_T_AWARD_TERMS_CONDITIONS": "T_AWARD_TERMS_AND_CONDITIONS",
    "X_T_BPA_PO_GA_ORG_ASSIGN_INTER": "T_BPA_PO_GA_ORG_ASSIGN_INTERFA",
    "X_T_EGP_ITEM_RELATIONSHIPS_INT": "T_EGP_ITEM_RELATIONSHIPS_INTF",
    "X_T_GL_SEGMENT_VALUES": "T_GL_SEGMENT_VALUES_INT",
    "X_T_INV_INVENTORY_LOC": "T_INV_INVENTORY_LOCATOR",
    "X_T_INV_INVENTORY_SUB": "T_INV_INVENTORY_SUBINVENTORY",
    "X_T_INV_ITEM_SUB": "T_INV_ITEM_SUBINVENTORY",
    "X_T_INV_TRANSACTIONS_INTER": "T_INV_TRANSACTIONS_INTERFACE",
    "X_T_MSC_ST_MEASURE_DATA_BOOK": "T_MSC_ST_MEASURE_DATA_BOOKINGS",
    "X_T_PO_LINE_LOC_INT": "T_PO_LINE_LOCATIONS_INTERFACE",
    "X_T_POZ_SITE_ASSIGN": "T_POZ_SITE_ASSIGNMENTS_INT",
    "X_T_POZ_SUP_ADDRESSES": "T_POZ_SUP_ADDRESSES_INT",
    "X_T_POZ_SUP_BUS_CLASS": "T_POZ_SUP_BUS_CLASS_INT",
    "X_T_POZ_SUP_CONT_ADDR": "T_POZ_SUP_CONTACT_ADDRESS_INT",
    "X_T_POZ_SUP_CONTACTS": "T_POZ_SUP_CONTACTS_INT",
    "X_T_POZ_SUPPLIER_SITES": "T_POZ_SUPPLIER_SITES_INT",
    "X_T_POZ_SUPPLIERS": "T_POZ_SUPPLIERS_INT",
    "X_T_RA_CUSTOMER_PROFILES_INT_A": "T_RA_CUSTOMER_PROFILES_INT_ALL",
    "X_T_RA_INT_DIST_ALL": "T_RA_INTERFACE_DISTRIBUTIONS",
    "X_T_WIS_WD_DETAILS_INT-ATOCMP": "T_WIS_WD_DETAILS_INT-ATO-CMP",
}


def _dbid(name):
    return DBID_OVERRIDES.get(name, name[2:])


def _app(dbid, steps):
    return {"dbid": dbid, "description": "",
            "steps": [{"order": i + 1, "func_type": ft, "func_name": fn}
                      for i, (ft, fn) in enumerate(steps)]}


applications = {}
for name in I_APPS:
    applications[name] = _app(_dbid(name), [("IF", name)])
for name in X_SIMPLE:
    applications[name] = _app(_dbid(name), [("EF", name)])
for name, efs in X_EXC.items():
    applications[name] = _app(_dbid(name), [("EF", ef) for ef in efs])

print(f"Apps: {len(I_APPS)} import, {len(X_SIMPLE) + len(X_EXC)} export "
      f"(simple {len(X_SIMPLE)} + exceptions {len(X_EXC)})")

mapping = load_mapping("FBDI_to_ApplaudTables_Mapping.xlsx")
mapped_tables = {info["applaud_table"] for info in mapping.values()
                 if str(info.get("applaud_table", "")).upper().startswith("T_")}

rows = derive_appmap(applications, mapped_tables)   # default: exclude *_VAL
write_appmap_workbook(rows, "FBDI_to_Applaud_AppMap.xlsx")

with_if = sum(1 for r in rows if r.import_files)
with_ef = sum(1 for r in rows if r.export_files)
none = [r.target_table for r in rows if not r.import_files and not r.export_files]
print(f"Wrote FBDI_to_Applaud_AppMap.xlsx: {len(rows)} tables "
      f"({with_if} with IF, {with_ef} with EF, {len(none)} with neither)")
print("Tables with NO IF/EF (Coverage gaps):")
for t in none:
    print(f"  - {t}")
