"""Generate the report's self-contained Definian CSS foundation.

Emits ``fbdi/templates/assets/definian.css`` — the Definian ``:root`` token block
(from the design system's ``colors_and_type.css``) plus ``@font-face`` rules for
only the handful of Aptos faces the FBDI Release Change Report actually uses, with
each face base64-inlined as a ``data:`` URL.

Why a subset: the design system's shipped ``definian.css`` embeds all 27 Aptos
faces (~2.5 MB). The report uses 5. Subsetting halves the size of every generated
report while keeping it a single portable file that renders identically in a
browser, in email, and through weasyprint (PDF) with no external font fetch.

This is a *build-time* helper. Its output is committed and is the runtime source
of truth — the external design-system directory is not needed to generate reports.
Re-run only when the face set changes.

Usage::

    py tools/build_report_font_css.py            # default design-system location
    py tools/build_report_font_css.py --design-system <path-to>/project

No third-party dependencies (stdlib ``base64`` only).
"""

from __future__ import annotations

import argparse
import base64
import re
import sys
from pathlib import Path

# Default design-system checkout (Brad's Windows layout). Override with
# --design-system for a different machine.
DEFAULT_DESIGN_SYSTEM = Path(
    r"C:\Users\10193\Definian\CodingAssistant\local\impeccable\definian-design-system\project"
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "fbdi" / "templates" / "assets" / "definian.css"

# (css font-family, weight, style, source .ttf). Keep this list minimal — every
# face here adds ~1.3x its file size to *every* generated report.
FACES = [
    ("Aptos", 400, "normal", "Aptos.ttf"),
    ("Aptos", 600, "normal", "Aptos-SemiBold.ttf"),
    ("Aptos", 700, "normal", "Aptos-Bold.ttf"),
    ("Aptos Display", 700, "normal", "Aptos-Display-Bold.ttf"),  # cover title only
    ("Aptos Mono", 400, "normal", "Aptos-Mono.ttf"),
]


def extract_root_block(css: str) -> str:
    """Return the first top-level ``:root { ... }`` block, braces balanced.

    Deliberately excludes everything above it (notably the ``@import`` of Inter
    Tight from Google Fonts) so the vendored asset has no external reference.
    """
    start = css.find(":root")
    if start == -1:
        raise ValueError("no :root block found in colors_and_type.css")
    brace = css.find("{", start)
    depth = 0
    for i in range(brace, len(css)):
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
            if depth == 0:
                return css[start : i + 1]
    raise ValueError(":root block is unbalanced in colors_and_type.css")


def font_face_rule(family: str, weight: int, style: str, ttf: Path) -> str:
    b64 = base64.b64encode(ttf.read_bytes()).decode("ascii")
    return (
        "@font-face{\n"
        f"  font-family:'{family}';\n"
        f"  font-weight:{weight};\n"
        f"  font-style:{style};\n"
        "  font-display:swap;\n"
        f"  src:url(data:font/ttf;base64,{b64}) format('truetype');\n"
        "}\n"
    )


def build(design_system: Path) -> str:
    fonts_dir = design_system / "fonts"
    tokens_css = design_system / "colors_and_type.css"
    if not tokens_css.is_file():
        raise SystemExit(f"colors_and_type.css not found at {tokens_css}")

    root_block = extract_root_block(tokens_css.read_text(encoding="utf-8"))

    faces = []
    for family, weight, style, name in FACES:
        ttf = fonts_dir / name
        if not ttf.is_file():
            raise SystemExit(f"font file not found: {ttf}")
        faces.append(font_face_rule(family, weight, style, ttf))

    header = (
        "/* ==========================================================================\n"
        "   Definian design foundation for the FBDI Release Change Report.\n"
        "   GENERATED by tools/build_report_font_css.py — do not hand-edit.\n"
        "   Tokens: design-system colors_and_type.css :root block (Inter @import dropped).\n"
        f"   Fonts: {len(FACES)} Aptos faces base64-inlined for a self-contained report.\n"
        "   ========================================================================== */\n"
    )
    # Strip the /* @kind ... */ inline annotations that only mean something to the
    # design-system tooling; they add noise to every report.
    root_block = re.sub(r"/\*\s*@kind[^*]*\*/", "", root_block)
    return header + "\n" + "".join(faces) + "\n" + root_block + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--design-system",
        type=Path,
        default=DEFAULT_DESIGN_SYSTEM,
        help="Path to the definian-design-system 'project' directory.",
    )
    args = parser.parse_args(argv)

    css = build(args.design_system)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(css, encoding="utf-8")
    size_mb = len(css.encode("utf-8")) / (1024 * 1024)
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({size_mb:.2f} MB, {len(FACES)} faces)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
